donkeyProgramming/TheAssetEditor

CommonControls/BaseDialogs/MathViews/DoubleViewModel.cs, CommonControls/Common/DirectoryHelper.cs, CommonControls/Services/PackFileService.cs
This looks kinda dumb, but it would avoid issues I have with packfiles getting corrupted or changes not saving if I try to save a pack in data while the game is running. If I close the game and then save the pack again it results in corruption or changes made to the pack not saving, no idea why. So we just fail earlier to avoid that.
This will also skip making the _temp pack and a backup.
=> don't do anything on save if we can't save existing packfile

CommonControls/PackFileBrowser/PackFileBrowserView.xaml.cs
the Focusable and Focus() doesn't seem needed and that part would cause the drag to not work if the user is too fast when starting with dragging the file
=> skip the focus when dragging treeview items

AssetEditor/Views/MainWindow.xaml.cs, CommonControls/PackFileBrowser/PackFileBrowserView.xaml, KitbasherEditor/ViewModels/SceneExplorerNodeViews/Rmv2/MaterialGeneralViewModel.cs
vanilla often uses `VariantMeshes` in wsmodels texture paths
=> ignore case if checking if a texture path exists

CommonControls/BaseDialogs/TextInputWindow.xaml.cs, CommonControls/PackFileBrowser/ContextMenuHandler.cs, CommonControls/PackFileBrowser/PackFileBrowserView.xaml, CommonControls/PackFileBrowser/PackFileBrowserView.xaml.cs, CommonControls/PackFileBrowser/PackFileBrowserViewModel.cs
Add two small features to improve usability:
* Add a Clear button on the pack browser sidebar - making it quicker for users to clear filters. Also added an auto focus, but I'm not 100% sure about adding the focus in the codebehind `PackFileBrowserView.xaml.cs`, but I'm a bit unfamiliar with WPF.
* Autofocus the text input when a dialog is opened for a new directory. This is just a constructor arg, so should be easy to apply to different `TextInputWindow` as needed. The default is false, just to remain as backward compatible as possible.
=> Focus input when creating a new dialog, add clear button to search

CommonControls/FileTypes/Sound/WWise/Common.cs, CommonControls/FileTypes/Sound/WWise/Hirc/V136/CAkRanSeqCntr_v136.cs
Adding missing stuff, some enums, not in last PR, woops.
Still no idea what's wrong with the RanSeqCntr.
=> Adding missing stuff from last PR, woops.

CommonControls/FileTypes/Sound/WWise/Hirc/HircParser.cs, CommonControls/FileTypes/Sound/WWise/Hirc/V136/CAkFxCustom_v136.cs, CommonControls/FileTypes/Sound/WWise/Hirc/V136/CAkFxShareSet_v136.cs, CommonControls/FileTypes/Sound/WWise/Hirc/V136/CAkMusicRanSeqCntr_v136.cs, CommonControls/FileTypes/Sound/WWise/Hirc/V136/CAkMusicSegment_v136.cs, CommonControls/FileTypes/Sound/WWise/Hirc/V136/CAkMusicSwitchCntr_v136.cs, CommonControls/FileTypes/Sound/WWise/Hirc/V136/CAkMusicTrack_v136.cs
MusicTrack, MusicSwitchCntr, MusicSegment, MusicRanSeqCntr, FxCustom, FxShareSet
Note that several double precision floats were decoded as uint64's in MusicTrack and MusicSegment.
And MusicSegment had a string "pMarkerName" whose length was given as an int32 rather than int16, so I just decoded that as a list of bytes.
Also FxShareSet ended up being the exact same as FxCustom, no idea what's up with that or if it even matters.
=> MusicTrack, MusicSwitchCntr, MusicSegment, MusicRanSeqCntr, FxCustom, FxShareSet

AssetManagment/AssetHandling/MeshImportExporter.cs, AssetManagment/AssetManagement_DependencyInjectionContainer.cs, AssetManagment/MeshHandling/MeshImportExporter.cs, AssetManagment/Strategies/Fbx/FbxAssetImporter.cs, CommonControls/Events/UiCommands/ImportAssetCommand.cs, CommonControls/Interfaces/AssetManagement/AssetConfigData.cs, CommonControls/Interfaces/AssetManagement/AssetManagerData.cs, CommonControls/Interfaces/AssetManagement/IAssetExporter.cs, CommonControls/Interfaces/AssetManagement/IAssetExporterProvider.cs, CommonControls/Interfaces/AssetManagement/IAssetImporterProvider.cs
Adds the basic interfaces and classes needed for adding (FBX) export.
Doesn't change the **basic** functionality, as that was already int there (see diagram)
- `IAssetManagementFactory` becomes `IAssetImportProvider` and  `IAssetExporterProvider`  as `IAssetManagementFactory` only had import support, and I do not know the intent for it. The 2 new interfaces works exactly the same way as the old one.
- ` IAssetImportProvider`/IAssetExporterProvider` provides `IAssetImporter` / `IAssetExporter`  respectvely, based on extension as before
- `IAssetExporter.ExportAsset(()` has  params for all _potential_ input data , AND config data which comes from the  UI
Data Flow Diagram
[Data Flow Diagram - AssetEditor FBX Export With Materials - Revision …
=> FBX Import/Export Interfaces

Audio/BnkCompiler/Compiler.cs, Audio/BnkCompiler/ObjectGeneration/BnkHeaderBuilder.cs, Audio/BnkCompiler/ResultHandler.cs
- Soundbanks now generate with the .bnk filetype extension.
- .dat files now generate into the correct folder.
=> Bugs Squashed:

AssetManagment/AnimationProcessing/SkeletonHelper.cs, AssetManagment/AssetBuilders/PackMeshBuilderHelpers.cs, AssetManagment/AssetBuilders/PackedMeshBuilder.cs, AssetManagment/AssetBuilders/VertexWeightCreator.cs, AssetManagment/MeshProcessing/Common/CommonWeightProcessor.cs, AssetManagment/MeshProcessing/Packed/PackedMeshProcessor.cs, CommonControls/FileTypes/Animation/AnimationFile.cs
Add; 
- `PackedMeshBuilder `updated to be more S.O.L.I.D, it is now "open closed". Its interface `IPackedMeshBuilder `has two implementations, `IndexedPackedMeshBuilder`, and `WeightedIndexedPackedMeshBuilder`.  the scene builder uses
`PackedMeshBuilderFactory.GetBuilder(AnimationFile skeletonFile)` to obtain the riggedd of non-rigged version as needed.
- `VertexWeightCreator` is used  to copy the 1-4 weights in an RMV2 vertex to 1 un-nested array, 
- Added  `Animations.GetIdFromBoneName(string name)` for save lookups (not out of range),  AnimationFile already has `string GetBoneNameFromId(int id)
- 2-3 minor helper classes
=> C# utlity classes for export. (Bottom-up)

Editors/KitbasherEditor/ViewModels/SceneExplorerNodeViews/Rmv2/MaterialGeneralViewModel.TextureViewModel.cs, Editors/KitbasherEditor/ViewModels/SceneExplorerNodeViews/Rmv2/MaterialGeneralViewModel.cs, Editors/KitbasherEditor/ViewModels/SceneExplorerNodeViews/Rmv2/MeshEditorViewModel.cs, Editors/KitbasherEditor/ViewModels/SceneExplorerNodeViews/SceneNodeViewFactory.cs, Editors/SimpleAnimationEditors/AnimationPack/AnimPackViewModel.cs, Editors/SimpleAnimationEditors/AnimationPack/Converters/AnimationBinWh3FileToXmlConverter.cs, Editors/SimpleAnimationEditors/AnimationPack/Converters/BaseAnimConverter.cs, Editors/TextureEditor/ViewModels/TextureEditorViewModel.cs, Editors/TextureEditor/ViewModels/TexturePreviewController.cs, Shared/GameFiles/AnimationPack/AnimationSlotType.cs, Shared/GameFiles/Shared.GameFormats.csproj, Shared/SharedCore/ErrorHandling/ErrorList.cs, Shared/SharedUI/BaseDialogs/ErrorListDialog/ErrorListView.xaml
Removed the old resource loader and changed them to use the new resource loader to load animation slots.txt
Implemented validation check for "cavalry" animations 
- Ensure that the animation time of mount and rider is exact (or close to within margin 0.000001)
- Ensure that the animation length of mount and rider is exact 
- Ensure that the version for both mount and rider is the same
- Ensure that any animation version difference in the splice for persistence (or in the current slot) matches with the animation itself
Also implemented yellow for warning in error list dialog
=> Animation validator & Embedded Resource Loader Fix

Editors/SimpleAnimationEditors/AnimationPack/Converters/AnimationBinWh3FileToXmlConverter.cs
a simple bug could prevent fragment from being saved, because it can't locate rider animation
=> minor bugfix in animation pack validator

GameWorld/View3D/SceneNodes/Rmv2MeshNode.cs, GameWorld/View3D/SceneNodes/Rmv2ModelNodeLoader.cs, GameWorld/View3D/Services/SceneSaving/Material/Strategies/WsModelGeneratorService.cs
Object names now populate properly, this results in proper wsModel generation.
=> Fix missing name for models when loading some rmv2 files for Pharao  #137

GameWorld/View3D/Services/SceneSaving/Material/Strategies/WsModelGeneratorService.cs, Shared/GameFiles/WsModel/WsModelMaterialFile.cs
This fixes the issues I listed in issue 141. Such as the material file creation naming and the shader naming for Pharaoh Total War specifically. The material file generation issue had some misnaming on the file name, as well as the shader being specified as one from other total war games.
=> Closes #141

Shared/SharedUI/BaseDialogs/PackFileBrowser/ContextMenuHandler.cs, Shared/SharedUI/DependencyInjectionContainer.cs, Shared/SharedUI/Events/UiCommands/DuplicateCommand.cs, Testing/E2EVerification/Shared/GameMock.cs, Testing/E2EVerification/UIEvent_Tests.cs
This solution should work for any file that has multiple extensions (no idea if there are any more, but decided to make it generic just in case). Tested by duplication multiple anm.meta files and checking that the values matched the originals.
=> Closes #124

Shared/SharedUI/Events/UiCommands/DuplicateFileCommand.cs
Fixed an issue with the packfile saving, also fixed an issue with a ArgumentOutOfBounds exception when substring would be run on a file without extension. I chose to make an extra helper method to clean up what is occurring in the execute function as well.
=> Fixes for duplicate command test cases

Editors/SimpleAnimationEditors/AnimationPack/Converters/AnimationBinWh3FileToXmlConverter.cs
added check if it can't find animation defined in the meta data somewhere
=> fixed null access when parsing animpack xml

GameWorld/ContentProject/Content/Shaders/Pbr/Capabilites/Tint.hlsli, GameWorld/View3D/Rendering/Materials/Capabilities/TintCapability.cs, GameWorld/View3D/Rendering/Materials/Shaders/CapabilityMaterial.cs, GameWorld/View3D/Rendering/Materials/Shaders/MetalRough/DefaultMaterial.cs, GameWorld/View3D/Rendering/Materials/Shaders/SpecGloss/DefaultMaterial.cs
Faction colored is "hardcoded" = enabled, which is fine, as meshes without faction color has no mask tex -> mask = {0,0,0,0] = faction coloring with not affect mesh.
=> Feat: Added per-model faction coloring and tinting, simple UI

Editors/Editors.ImportExport/Exporting/Exporters/DdsToMaterialPng/DdsToMaterialPngExporter.cs, Editors/Editors.ImportExport/Exporting/Exporters/DdsToNormalPng/DdsToNormalPngExporter.cs, Editors/Editors.ImportExport/Exporting/Exporters/RmvToGltf/Helpers/GltfMeshBuilder.cs
- DDS to PNG Texture saving to disk (for Rmv2ToGltf) was disabled, with NotImpl throws
- Gltf vertex weights/joint indices were not being set, were all 0
=> Fix: Issues: Textures saving, and vertex weights

Shared/SharedUI/BaseDialogs/PackFileBrowser/ContextMenuHandler.cs
Fix: severe pack path addition error, caused by method allowed mixed case, while AE pack paths are strictly lower case
added wrapper for file/folder value editor
=> Fix: severe pack path addition error, caused by method allowed mixed case, while AE pack paths are strictly lower case

AssetEditor/spellingexclusions.dic, Editors/Editors.ImportExport/Exporting/Exporters/DdsToMaterialPng/DdsToMaterialPngExporter.cs, Editors/Editors.ImportExport/Exporting/Exporters/DdsToNormalPng/DdsToNormalPngExporter.cs, Editors/Editors.ImportExport/Exporting/Exporters/RmvToGltf/Helpers/GltfMeshBuilder.cs, Editors/Editors.ImportExport/Exporting/Exporters/RmvToGltf/Helpers/GltfSkeletonCreator.cs, Editors/Editors.ImportExport/Exporting/Exporters/RmvToGltf/RmvToGltfExporter.cs, Editors/Editors.ImportExport/Exporting/Presentation/ExportWindow.xaml, Editors/Editors.ImportExport/Exporting/Presentation/RmvToGltf/RmvToGltfExporterViewModel.cs, Editors/Editors.ImportExport/Importing/Importers/GltfToRmv/GltfImporter.cs, Editors/Editors.ImportExport/Importing/Importers/GltfToRmv/Helper/RmvMeshBuilder.cs
Users had some issues at the very first real world test of the export.
**Changes**
- SystemPath text box is read-only, browse button only way.
- Browse button was non-functional, fixes
- DDS file paths from RMV2, that are not found are skipped (proper paths are in WSMODEL/XMLMATERIAL files)
- Corrected some output path issues which generated invalid paths
EDIT:
- Skeleton Name (aka skeleton id string) is stored gltf , and read by importer; 
- Skeleton Name is added as gltf scene node, for maximum compatibility when re-saving scene or converting to other formats, and so the user can edit / add a skeleton id string to gltf if needed
- Addes many more checks/throws for potentially invalid containers
- Fixed path issues with exporter PNG saving
=> Fixes for Gltf Export Bugs Reported  by Users

GameWorld/View3D/Rendering/Materials/Serialization/WsMaterialTemplateEditor.cs, Shared/EmbeddedResources/Resources/WsModelTemplates/MaterialTemplate_pharaoh_default.xml, Testing/GameWorld.Core.Test/Rendering/Shaders/SpecGloss/DefaultMaterialTests.cs, Testing/GameWorld.Core.Test/WsMaterialTemplate/CapabilityMaterialMock.cs, Testing/GameWorld.Core.Test/WsMaterialTemplate/WsMaterialTemplateTests.cs
I verified in game that these changes are working to make the pharaoh wsmodels and material that are generated work in game. We had a couple of issues, the first was the naming of the files where things like weighted_2_character should have been weighted_standard_2. We also had issues revolving around the pharaoh material template. It was pointing to the wrong shaders and naming them improperly. I created tests with a capability material mock class to test that the naming was accurate in the file names. There are six unit tests total.
=> Pharaoh WsModel generation fixes, material generation fixes and some unit tests
