donkeyProgramming/TheAssetEditor

CommonControls/Services/PackFileService.cs, CommonControls/Services/SkeletonAnimationLookUpHelper.cs
this can save 500ms on app launch from my limited testing, but may not be needed/worthwhile
=> Parallel.For when loading CA packs

CommonControls/PackFileBrowser/PackFileBrowserViewModel.cs
=> fix for duplicate files in treeview when adding file with same name

CommonControls/FileTypes/PackFiles/Models/PackFileDataBase.cs, CommonControls/PackFileBrowser/ContextMenuHandler.cs, CommonControls/PackFileBrowser/PackFileBrowserViewModel.cs, CommonControls/Services/PackFileService.cs
hope I didn't miss anything with how this all works
=> folder renaming

KitbasherEditor/ViewModels/KitbasherViewModel.cs, View3D/Components/Component/CommandExecutor.cs
=> fix for not checking if undo is made after saving

AnimationEditor/Common/AnimationPlayer/AnimationPlayerViewModel.cs, CommonControls/Common/MathUtil.cs, View3D/Animation/AnimationClip.cs, View3D/Animation/AnimationPlayer.cs, View3D/Utility/TimeSpanExtension.cs
In the first two commits, I fixed the stuck frame using floating numbers
After, I decided to reimplement the time tracking using long integers to avoid using float numbers
=> Stuck frame fix via using long microseconds

AssetEditor/ViewModels/SettingsViewModel.cs, AssetEditor/Views/MainWindow.xaml, AssetEditor/Views/MainWindow.xaml.cs, AssetEditor/Views/Settings/SettingsView.xaml, CommonControls/Services/ApplicationSettingsService.cs, KitbasherEditor/ViewModels/KitbasherViewModel.cs, KitbasherEditor/ViewModels/MenuBarViews/MenuBarViewModel.cs, KitbasherEditor/ViewModels/MenuBarViews/ToolActions.cs, KitbasherEditor/ViewModels/SceneExplorerNodeViews/ISceneNodeViewModel.cs, KitbasherEditor/ViewModels/SceneExplorerNodeViews/Rmv2/MaterialGeneralViewModel.cs, KitbasherEditor/ViewModels/SceneExplorerNodeViews/Rmv2/MeshEditorViewModel.cs, KitbasherEditor/ViewModels/SceneExplorerViewModel.cs, KitbasherEditor/Views/EditorViews/Rmv2/MaterialGeneralView.xaml, View3D/SceneNodes/Rmv2MeshNode.cs, View3D/Services/LodGenerationService.cs
Hello, olle. 
Because I will need to port lots of warhammer 2 assets to game 3, I implemented some of QoL improvement that could help the users to port their assets (notably the texture selection panel) or improve the overall usability of the program.
1. Option to hide Warhammer 2 texture selectors if the user selects Warhammer 3.
Before:  
After:  
Justification: It reduces clutter and cognitive load when picking textures since these param `Diffuse, Specular, Gloss` don't matter in game 3 anyway. To enable it, simply tick the option in the Settings menu.
2. Option to copy first lod to every lod slots
Justification: Some special models like LL, heroes, or generic lords (subjectively) need to be in high quality and with this option the user can populate the whole LOD slot with the same …
=> Collections of QoL improvements

KitbasherEditor/ViewModels/MenuBarViews/MenuBarViewModel.cs, View3D/Services/Rmv2UpdaterService.cs
First attemp, needs fine tuning,
=> first WH2->WH3 texture conversion,

CommonControls/FileTypes/Sound/WWise/Hirc/HircParser.cs, CommonControls/FileTypes/Sound/WWise/Hirc/V136/CAkLayerCntr_v136.cs, CommonControls/FileTypes/Sound/WWise/Hirc/V136/CAkRanSeqCntr_v136.cs, CommonControls/FileTypes/Sound/WWise/Hirc/V136/CAkSwitchCntr_v136.cs, CommonControls/FileTypes/Sound/WWise/Hirc/V136/Common.cs
HIRC LayerContainer, RanSeqContainer, SwitchContainer for v136.
Note that about half of RanSeqContainers still do not decode.
=> HIRC LayerContainer, RanSeqContainer, SwitchContainer for v136.

CommonControls/FileTypes/Sound/WWise/Hirc/HircParser.cs, CommonControls/FileTypes/Sound/WWise/Hirc/V136/CAkDialogueEvent_v136.cs
I made all the nodes in the trees just regular "Node", commented out "SoundNode" which I think were used for the leaves in the v128 version. Not sure that effects much. I also don't know enough about C#'s classes and stuff to add them back in.
=> DialogueEvents for v136. No errors.

CommonControls/FileTypes/MetaData/Definitions/SpliceOverride.cs
Basically just the same as SPLICE, but with an extra boolean
=> decoded SPLICE_OVERRIDE v12

.github/workflows/pr-build.yml, .github/workflows/pr-test.yml
As the title says. Hope this is useful for PR reviewing in the future.
=> Add Github Actions for building and testing

Audio/FileFormats/WWise/Hirc/V136/CAkDialogueEvent_v136.cs, Audio/FileFormats/WWise/Hirc/V136/CAkMusicSwitchCntr_v136.cs, Audio/Utility/AudioResearchHelper.cs, AudioResearch/Program.cs
=> Implement naive serialization for DialogueEvent_v136

CommonControls/PackFileBrowser/ContextMenuHandler.cs
This is preparation for the FBX SDK.
Disables Assimp invokation, but does not delete its files.
=> This disables (but not removes) Assimp.

Audio/FileFormats/WWise/Hirc/HircFactory.cs, Audio/FileFormats/WWise/Hirc/HircInterfaces.cs, Audio/FileFormats/WWise/Hirc/V112/CAkActorMixer_v112.cs, Audio/FileFormats/WWise/Hirc/V112/CAkLayerCntr_v112.cs, Audio/FileFormats/WWise/Hirc/V112/CAkSwitchCntr_V112.cs, Audio/FileFormats/WWise/Hirc/V136/CAkActorMixer_v136.cs, Audio/FileFormats/WWise/Hirc/V136/CAkLayerCntr_v136.cs, Audio/FileFormats/WWise/Hirc/V136/CAkSwitchCntr_v136.cs, Audio/Presentation/AudioExplorer/AudioEditorMainView.xaml, Audio/Presentation/AudioExplorer/AudioEditorViewModel.cs, Audio/Storage/WWiseBnkLoader.cs, Audio/Utility/SoundPlayer.cs, Audio/Utility/WWiseTreeParserBase.cs, Audio/Utility/WWiseTreeParserParent.cs
The Audio Editor can now be used with Total War Attila packfiles.
The HIRC JSON editor text box now has a scrollbar for easily navigating through large JSON objects.
=> Support TW Attila in Audio Explorer, add scrollbar to HIRC JSON editor

Audio/BnkCompiler/AudioFileImporter.cs, Audio/BnkCompiler/CompilerData.cs, Audio/BnkCompiler/ObjectGeneration/HircSorter.cs, Audio/BnkCompiler/ObjectGeneration/Warhammer3/RandomContainerGenerator.cs, Audio/BnkCompiler/ObjectGeneration/Warhammer3/SoundGenerator.cs, Audio/BnkCompiler/ProjectLoader.cs
Change Notes:
- Fixed some random container generation bugs
- Fixed some hirc sorting bugs
=> Fixed bugs

AnimationMeta/FileTypes/Definitions/AnimatedProp.cs, AnimationMeta/FileTypes/Definitions/Prop.cs
(animated) Prop v15 support for wh3
=> (animated) Prop v15 support for wh3

Editors/KitbasherEditor/ViewModels/SceneExplorerNodeViews/Rmv2/MaterialGeneralViewModel.TextureViewModel.cs, Editors/KitbasherEditor/ViewModels/SceneExplorerNodeViews/Rmv2/MaterialGeneralViewModel.cs, Editors/KitbasherEditor/ViewModels/SceneExplorerNodeViews/Rmv2/MeshEditorViewModel.cs, Editors/KitbasherEditor/ViewModels/SceneExplorerNodeViews/SceneNodeViewFactory.cs, Editors/TextureEditor/ViewModels/TextureEditorViewModel.cs, Editors/TextureEditor/ViewModels/TexturePreviewController.cs
Restored texture viewer. TODO. fix the dark theme on texture viewer
=> fix broken texture viewer due to eventhub is not defined

AnimationEditor/AnimationKeyframeEditor/AnimationKeyframeEditorViewModel.cs, AnimationEditor/AnimationKeyframeEditor/EditorView.xaml, AnimationEditor/MountAnimationCreator/EditorView.xaml, AnimationEditor/MountAnimationCreator/MountAnimationCreatorViewModel.cs, Editors/KitbasherEditor/ViewModels/MenuBarViews/MenuBarViewModel.cs, Editors/SimpleAnimationEditors/AnimationPack/Converters/AnimationBinWh3FileToXmlConverter.cs
- added copy animation from mount tool to animation keyed frame. 
also bugfixes on:
- scale tool on kitbasher
- validator on animpack compiler
=> added copy animation from mount tool to animation keyed frame. also bugfixes

Shared/GameFiles/AnimationPack/CampaignAnimationBin.cs, Shared/SharedCore/ByteParsing/ChuckWriter.cs
=> fix capitalisation bug in campaign animation bin writer/parser

AssetEditor/DevConfigs/Configs/KitbashTool.cs, AssetEditor/Properties/launchSettings.json, Editors/Editors.ImportExport/Common/GlobalSceneTransforms.cs, Editors/Editors.ImportExport/Editors.ImportExport.csproj, Editors/Editors.ImportExport/Exporting/Exporters/RmvToGltf/Helpers/GltfAnimationCreator.cs, Editors/Editors.ImportExport/Exporting/Exporters/RmvToGltf/Helpers/GltfSkeletonCreator.cs, Editors/Editors.ImportExport/Exporting/Exporters/RmvToGltf/Helpers/SkeletalAnimationMath.cs, Editors/Editors.ImportExport/Exporting/Exporters/RmvToGltf/Helpers/VectorConverter.cs, Editors/Editors.ImportExport/Exporting/Exporters/RmvToGltf/RmvToGltfExporter.cs, Editors/Editors.ImportExport/Exporting/Presentation/DdsToPng/DdsToPngExporterViewModel.cs, Editors/Editors.ImportExport/Exporting/Presentation/RmvToGltf/RmvToGltfExporterViewModel.cs
One can export animations from AnimationFile, to GLTF
=> Animation Export to GLTF for Asset Editoir

Shared/SharedUI/BaseDialogs/PackFileBrowser/EditFileNameDialog.cs
Issues: Dialog Box Text Box was empty after the dialog box was shown again, after enter invalid input.
=> Fixes Minor Bug in PackFileBrowser.EditFileNameDialog

AssetEditor/ViewModels/MainViewModel.cs, Shared/SharedCore/Services/IStandardDialogs.cs, Shared/SharedUI/BaseDialogs/PackFileTree/ContextMenu/Commands/OpenPackInFileExplorerCommand.cs, Shared/SharedUI/BaseDialogs/PackFileTree/ContextMenu/MainApplicationContextMenuBuilder.cs, Shared/SharedUI/BaseDialogs/PackFileTree/PackFileBrowserViewModel.cs, Shared/SharedUI/BaseDialogs/PackFileTree/PackFileTreeViewFactory.cs, Shared/SharedUI/BaseDialogs/PackFileTree/SearchFilter.cs, Shared/SharedUI/BaseDialogs/StandardDialog/PackFile/PackFileBrowserWindow.xaml.cs, Shared/SharedUI/BaseDialogs/StandardDialog/PackFile/SavePackFileWindow.xaml.cs, Shared/SharedUI/BaseDialogs/StandardDialog/StandardDialogs.cs, Shared/SharedUI/DependencyInjectionContainer.cs
- Added folder only browsing.
- Added context menu functionality for opening the location of a pack file in the Windows file explorer.
=> PackFileBrowsing

AssetEditor/Properties/launchSettings.json, Editors/Audio/DependencyInjectionContainer.cs, Editors/Audio/Storage/AudioRepository.cs, Editors/Audio/Storage/BnkLoader.cs, Editors/Audio/Storage/DatLoader.cs, Editors/Audio/Storage/RepositoryProvider.cs, Editors/Kitbashing/KitbasherEditor/DevConfig/Kitbash_RomeShield.cs, Editors/Kitbashing/Test.KitbashEditor/KitbashEditor_SaveTests.cs, GameWorld/View3D/Rendering/Materials/CapabilityMaterialFactory.cs, Shared/GameFiles/Dat/SoundDatFile.cs, Shared/SharedCore/Settings/GameInformationFactory.cs, Testing/GameWorld.Core.Test/Rendering/Materials/CapabilityMaterialFactoryTests.cs, Testing/GameWorld.Core.Test/Services/SceneSaving/GeometrySaveSettingsTests.cs
Change Notes:
- Added bank generator version info to the game info factory.
- Incorporated game bank generator version check into the AudioRepository.
- Did a bit of refactoring of the AudioRepository.
- Added some more info to the AudioRepository for use in the AudioEditor.
- Some general maintenance.
=> Added some game Wwise info and incorporated checks for it in the AudioRepository.

Editors/Audio/AudioExplorer/AudioExplorerViewModel.cs, Shared/SharedCore/PackFiles/Models/DataSource.cs, Shared/SharedCore/PackFiles/Models/PackFileContainer.cs, Shared/SharedCore/PackFiles/PackFileDecrypter.cs, Shared/SharedCore/PackFiles/PackFileEncrypter.cs, Shared/SharedCore/PackFiles/PackFileSerializer.cs, Testing/Shared.Core.Test/PackFiles/PackFileEncryptionTests.cs
- Added pack file decryption and encryption classes.
- Added encryption tests.
- Updated the AudioExplorer to play ICAkMusicTrack .wem files.
=> Added PackFile decryption which means music .wem files now play (only packs containing music wems were encrypted)
